export const employeeList = [
  {
    id: "01",
    firstName: "Sam",
    lastName: "Smith",
    age: 24,
    gender: "male",
    address: "",
    mobile: "9090909090",
    email: "sam.smith@gmail.com",
    dob: "04/09/1990",
    profilePic: "",
  },
  {
    id: "02",
    firstName: "Tessy",
    lastName: "Smith",
    age: 29,
    gender: "female",
    address: "",
    mobile: "4534224560",
    email: "tessy.smith@gmail.com",
    dob: "23/02/1990",
    profilePic: "",
  },
  {
    id: "03",
    firstName: "Pete",
    lastName: "Smith",
    age: 26,
    gender: "male",
    address: "",
    mobile: "8978675643",
    email: "pete.smith@gmail.com",
    dob: "20/11/1990",
    profilePic: "",
  },
];
